// TODO: fix candor so that callback isn't always nil

setTimeout(callback, interval) {
  scope uv, print
  print("{ callback:", callback, "}")
  timer = uv.newTimer()
  uv.timerStart(timer, interval, 0)
  timer.onTimer = () {
    scope uv, timer, callback, print
    uv.close(timer)
    callback()
    print("{ callback:", callback, "}")
  }
  return timer
}

setTimeout(() {
  scope print
  print("Hello World!")
}, 500)
