print = global.print
uv = global.uv

// Simple pretty printer
dump(value) {
  type = typeof value
  if (type == "nil") {
    return "nil"
  }
  if (type == "boolean" || type == "number") {
    return "" + value
  }
  if (type == "string") {
    return '"' + value + '"'
  }
  if (type == "object") {
    keys = keysof value
    length = sizeof keys
    i = 0
    escaped = "{ "
    while (i < length) {
      key = keys[i]
      part = dump(value[key])
      escaped = escaped + key + ": " + part
      if (i < length - 1) {
        escaped = escaped + ", "
      }
      i++
    }
    return escaped + " }"
  }
  if (type == "array") {
    length = sizeof value
    i = 0
    escaped = "[ "
    while (i < length) {
      escaped = escaped + dump(value[i])
      print(escaped)
      if (i < length - 1) {
        escaped = escaped + ", "
      }
      i++
    }
    return escaped + " ]"
  }
  return "[" + type + "]"
}

// Quick and dirty pretty printer
p(label, value) {
  print(label, dump(value))
}

p("uv", uv)

timer = uv.createTimer()
__$gc()
timer2 = uv.createTimer()
__$gc()

timer.start(timer, 2400, 0, () {
  __$gc()
  print("onTimeout")
  __$gc()
  __$gc()
  timer2.stop(timer2)
  timer.stop(timer)
  __$gc()
  timer.close(timer, () {
    __$gc()
    print("close1")
  })
  __$gc()
  timer2.close(timer2, () {
    __$gc()
    print("close2")
  })
  __$gc()
})
__$gc()

timer2.start(timer2, 333, 333, () {
  __$gc()
  print("onInterval")
  period = timer2.getRepeat(timer2)
  __$gc()
  p("period", period)
  timer2.setRepeat(timer2, period / 1.2 + 1)
  __$gc()
})
__$gc()

p("timer", timer)
p("timer2", timer2)
