print = global.print
p = global.prettyPrint
require = global.require

Timer = require('timer')
p("Timer", Timer)

timer = Timer.create()
timer2 = Timer.create()

Timer.start(timer, 2400, 0, () {
  p("onTimeout", timer)
  Timer.stop(timer2)
  Timer.stop(timer)
  Timer.close(timer, () {
    p("close", timer)
  })
  Timer.close(timer2, () {
    p("close2", timer2)
  })
})

Timer.start(timer2, 333, 333, () {
  p("onInterval", timer2)
  period = Timer.getRepeat(timer2)
  p("period", period)
  Timer.setRepeat(timer2, period / 1.2 + 1)
})

p("timer", timer)
p("timer2", timer2)
