print = global.print

Rectangle = {}
Rectangle.getArea = (self) {
  return self.w * self.h
}
Rectangle.initialize = (self, w, h) {
  self.w = w
  self.h = h
}

Square = new Rectangle
Square.initialize = (self, s) {
  self.w = s
  self.h = s
}

rect = new Rectangle
rect:initialize(3, 5)
print("Rectangle 3x5 =", rect:getArea())

square = new Square
square:initialize(4)
print("Square 4x4 =", square:getArea())