print = global.print
p = global.prettyPrint
require = global.require

Timer = require('timer')
p("Timer", Timer)

timer = Timer.create()
timer2 = Timer.create()

p("timer", timer)
p("timer2", timer2)

timer:start(2400, 0, () {
  p("onTimeout", timer)
  timer2:stop()
  timer:stop()
  timer:close(() {
    p("close", timer)
  })
  timer2:close(() {
    p("close2", timer2)
  })
})

timer2:start(333, 333, () {
  p("onInterval", timer2)
  period = timer2:getRepeat()
  p("period", period)
  timer2:setRepeat(period / 1.2 + 1)
})

p("timer", timer)
p("timer2", timer2)
