print = global.print
Timer = global.uv.Timer

timer = Timer.create()
timer2 = Timer.create()

Timer.start(timer, 2400, 0, () {
  print("onTimeout")
  Timer.stop(timer2)
  Timer.stop(timer)
  Timer.close(timer, () {
    // Can't use `print` here, it's not a function, have to use `global.print`
    global.print("close1", print)
  })
  Timer.close(timer2, () {
    // Can't use `print` here, it's not a function, have to use `global.print`
    global.print("close2", print)
  })
})

Timer.start(timer2, 333, 333, () {
  Timer = global.uv.Timer
  print("onInterval")
  period = Timer.getRepeat(timer2)
  print("period", period)
  Timer.setRepeat(timer2, period / 1.2 + 1)
})

print("timer", timer)
print("timer2", timer2)
