print = global.print
p = global.prettyPrint

Object = {
  "new": (self, args...) {
    obj = new self
    if (obj.initialize) obj:initialize(args...)
    return obj
  }
}

Rectangle = new Object
Rectangle.getArea = (self) {
  return self.w * self.h
}
Rectangle.initialize = (self, w, h) {
  self.w = w
  self.h = h
}
p("Rectangle", Rectangle)

Square = new Rectangle
Square.initialize = (self, s) {
  self.w = s
  self.h = s
}
p("Square", Square)

rect = Rectangle:new(3, 5)
p("rect", rect)
print("Rectangle 3x5 = " + rect:getArea())

square = Square:new(4)
p("square", square)
print("Square 4x4 = " + square:getArea())
